const types: FilterTypes = {
  accounting: "Księgowość",
  airport: "Lotnisko",
  amusement_park: "Park rozrywki",
  aquarium: "Akwarium",
  art_gallery: "Galeria sztuki",
  atm: "Bankomat",
  bakery: "Piekarnia",
  bank: "Bank",
  bar: "Bar",
  beauty_salon: "Salon piękności",
  book_store: "Księgarnia",
  bowling_alley: "Kręgielnia",
  cafe: "Kawiarnia",
  campground: "Kemping",
  casino: "Kasyno",
  city_hall: "Ratusz",
  clothing_store: "Sklep z ciuchami",
  convenience_store: "Artykuły codziennego użytku",
  department_store: "Dom towarowy",
  embassy: "Ambasada",
  fire_station: "Remiza strażacka",
  florist: "Kwiaciarnia",
  gas_station: "Stacja benzynowa",
  gym: "Siłownia",
  hair_care: "Pielęgnacja włosów",
  hardware_store: "Sklep budowlany",
  jewelry_store: "Jubiler",
  library: "Biblioteka",
  liquor_store: "Sklep monopolowy",
  lodging: "Pensjonat",
  meal_delivery: "Jedzenie na dowóz",
  meal_takeaway: "Jedzenie na wynos",
  mosque: "Meczet",
  movie_rental: "Wypożyczalnia filmów",
  movie_theater: "Teatr",
  museum: "Muzeum",
  night_club: "Klub nocny",
  park: "Park",
  parking: "Parking",
  pet_store: "Sklep zoologiczny",
  pharmacy: "Apteka",
  post_office: "Poczta",
  restaurant: "Restauracja",
  shopping_mall: "Centrum handlowe",
  spa: "Spa",
  stadium: "Stadion",
  store: "Sklep",
  subway_station: "Stacja metra",
  supermarket: "Supermarket",
  synagogue: "Synagoga",
  taxi_stand: "Postój taksówek",
  tourist_attraction: "Atrakcja turystyczna",
  train_station: "Dworzec kolejowy",
  travel_agency: "Agencja podróży",
  university: "Uniwersytet",
  zoo: "Zoo",
};

export default types;
